[project]
name = "termkey"
version = "0.17.4"
authors = ["Ben Longbons <b.r.longbons@gmail.com>"]
build = [
    "./install_termkey.sh",
    "./generate_link.sh"
]

[[lib]]
name = "termkey"
# path = "src/lib.rs"
crate_type = ["dylib"]
test = false

# [[example]]
# name = "demo-sync"
# path = "examples/demo-sync.rs"

# [[example]]
# name = "demo-async"
# path = "examples/demo-async.rs"
